[package]
name = "socks-hub"
version = "0.1.1"
license = "MIT"
repository = "https://github.com/ssrlive/socks-hub"
homepage = "https://github.com/ssrlive/socks-hub"
authors = ["ssrlive", "cssivision <cssivision@gmail.com>"]
description = "http or socks to socks proxy."
readme = "README.md"
edition = "2021"

[dependencies]
base64 = "0.21"
bytes = "1.5"
clap = { version = "4.4", features = ["derive"] }
ctrlc2 = { version = "3.5", features = ["termination", "tokio"] }
dotenvy = "0.15"
env_logger = "0.11"
http-body-util = "0.1"
hyper = { version = "1.1", features = ["full"] }
log = "0.4"
pin-project-lite = { version = "0.2.4" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
socks5-impl = "0.5"
tokio = { version = "1", features = ["full"] }
