[package]
name = "http2socks"
version = "0.1.0"
license = "MIT"
repository = "https://github.com/cssivision/http2socks"
homepage = "https://github.com/cssivision/http2socks"
authors = ["cssivision <cssivision@gmail.com>"]
description = "http to socks proxy."
readme = "README.md"
edition = "2021"

[dependencies]
base64 = "0.21"
clap = { version = "4.4", features = ["derive"] }
dotenvy = "0.15"
env_logger = "0.11"
hyper = { version = "0.14", features = ["full"] }
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
socks5-impl = "0.5"
tokio = { version = "1", features = ["full"] }
