[package]
name = "socks-hub"
version = "0.1.10"
license = "MIT"
repository = "https://github.com/ssrlive/socks-hub"
homepage = "https://github.com/ssrlive/socks-hub"
authors = ["ssrlive", "cssivision <cssivision@gmail.com>"]
description = "http or socks to socks proxy."
readme = "README.md"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib", "lib"]

[features]
default = ["acl"]
acl = ["idna", "ipnet", "iprange", "once_cell", "regex"]

[dependencies]
as-any = "0.3"
base64 = "0.22"
bytes = "1.5"
chrono = "0.4"
clap = { version = "4.5", features = ["derive"] }
ctrlc2 = { version = "3.5", features = ["termination", "tokio"] }
dotenvy = "0.15"
env_logger = "0.11"
http-body-util = "0.1"
hyper = { version = "1.1", features = ["full"] }
idna = { version = "0.5", optional = true }
ipnet = { version = "2.9", optional = true }
iprange = { version = "0.6", optional = true }
log = "0.4"
once_cell = { version = "1.19", optional = true }
pin-project-lite = { version = "0.2" }
regex = { version = "1.10", optional = true }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
socks5-impl = "0.5"
tokio = { version = "1", features = ["full"] }
