[package]
name = "socks-hub"
version = "0.1.15"
license = "MIT"
repository = "https://github.com/ssrlive/socks-hub"
homepage = "https://github.com/ssrlive/socks-hub"
authors = ["ssrlive", "cssivision <cssivision@gmail.com>"]
description = "Convert http proxy or socks5 proxy to socks5 proxy."
readme = "README.md"
edition = "2021"
rust-version = "1.80"

[lib]
crate-type = ["staticlib", "cdylib", "lib"]

[features]
default = ["sockshub", "acl"]
acl = [
    "idna",
    "ipnet",
    "iprange",
    "once_cell",
    "regex",
    "socks5-impl",
    "tokio",
    "log",
]
base64 = ["dep:base64"]
sockshub = [
    "base64",
    "socks5-impl",
    "tokio",
    "ctrlc2",
    "env_logger",
    "serde",
    "serde_derive",
    "serde_json",
    "clap",
    "chrono",
    "http-body-util",
    "hyper",
    "dotenvy",
    "as-any",
    "bytes",
    "pin-project-lite",
    "log",
]

[dependencies]
as-any = { version = "0.3", optional = true }
base64 = { version = "0.22", optional = true }
bytes = { version = "1.6", optional = true }
cfg-if = "1.0"
chrono = { version = "0.4", optional = true }
clap = { version = "4.5", features = ["derive"], optional = true }
ctrlc2 = { version = "3.5", features = [
    "termination",
    "tokio",
], optional = true }
dotenvy = { version = "0.15", optional = true }
env_logger = { version = "0.11", optional = true }
http-body-util = { version = "0.1", optional = true }
hyper = { version = "1.2", features = ["full"], optional = true }
idna = { version = "1.0", optional = true }
ipnet = { version = "2.9", optional = true }
iprange = { version = "0.6", optional = true }
log = { version = "0.4", optional = true }
once_cell = { version = "1.19", optional = true }
pin-project-lite = { version = "0.2", optional = true }
regex = { version = "1.10", optional = true }
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }
serde_json = { version = "1.0", optional = true }
socks5-impl = { version = "0.6", default-features = false, features = [
    "client",
    "server",
], optional = true }
tokio = { version = "1", features = ["full"], optional = true }

[[bin]]
name = "socks-hub"
required-features = ["sockshub", "acl"]
