language = "C"
cpp_compat = true

[export]
include = ["socks_hub_run", "socks_hub_set_log_callback", "socks_hub_stop"]
exclude = []

[export.rename]
"ArgVerbosity" = "SocksHubVerbosity"
"ProxyType" = "SocksHubProxyType"

[enum]
prefix_with_name = true
